name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Write .clasp.json
        run: |
          echo '{
            "scriptId":"11qn78SG8gk7NAfwoOBVR5L57VkHSWh_yTaSXTqMfcMuqNF5Seap8BngQ",
            "rootDir": "."
          }' > .clasp.json

      - name: Write .clasprc.json file
        run: |
          echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json

      - name: Deploy to Google Apps Script
        run: clasp push --force
